---
functional:
  - требование 1
  - требование 2
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестировать на совместимость с последними версиями браузеров
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен обрабатывать большое количество трафика
implicit:
  - Интерфейс сайта должен быть в умеренной цветовой гамме
  - Шрифт сайта должен быть понятным и корректным
